### ISSUE TITLE
zero_grad for accumulation_steps = 1 not working as expected

### ISSUE THREAD

**Issue by abdurrehman11** [abhishekkrthakur/tez#38]
As far as I know, in normal execution flow for zero_grad and forward pass, first we zero_gard for each batch and then do the forward pass but I investigated that in code, it is not happening in this way when accumualtion_steps =1 and batch =1, first forward pass executes first without doing zero_grad.

I tried to reproduce it and it is doing the same which I explained above.

![image](https://user-images.githubusercontent.com/24878579/160200428-b89d884d-ee2d-4f1c-837c-9949d8931e27.png)

Also, I think we can fix this by removing condition in the tez.py file on line # 330, 331.

**Comment by abhishekkrthakur** [comment]
it should be fixed in main branch now. could you please confirm?

**Comment by abdurrehman11** [comment]
This issue still exists in main branch as well as I did not see any fix for it.

**Comment by abhishekkrthakur** [comment]
hmm... then i might be missing something. could you please share more information/code? i see that the zero grads as fine. or i missed something?

**Comment by abdurrehman11** [comment]
I just run the latest tez code and same issue is still happening. 

![image](https://user-images.githubusercontent.com/24878579/160281072-77f1cfcb-c44d-4159-87ab-bf07aa34d310.png)

Here, you can see when batch_index = 0, it will first zero_grad and then forward pass will run and it is fine but when batch_index = 1, this condition will not run so forward pass will run without doing zero_grad first as in below snapshot.

![image](https://user-images.githubusercontent.com/24878579/160281125-8949d7f1-652f-4353-8788-b4725c95c1b0.png)

So, one solution is to either remove if condition on zero_grad in _step() on line # 336 OR remove the `self.batch_index == 0` on line # 299 OR you can come with some other fix which you know better. 

Hope it helps.

**Comment by abhishekkrthakur** [comment]
it seems like one of us is confused. when batch_index = 1 or any value greater than zero,  zero_grad is happening here: https://github.com/abhishekkrthakur/tez/blob/fd2d85e6e311e47fdd9edd189605a30dc58b463e/tez/model/tez.py#L336. This zero_grad is _before_ the forward pass. 

when batch_index = 0, `_step` function does the zero grad. this zero_grad is before the very first forward pass.

**Comment by abdurrehman11** [comment]
I tried to log the forward pass and zero_grad (wherever it is written in code) like this,

![image](https://user-images.githubusercontent.com/24878579/160283390-87cae25f-71f7-4332-8ed7-98e28e8a9efa.png)

![image](https://user-images.githubusercontent.com/24878579/160283487-967418aa-1ad3-431e-a062-b5a975afb172.png)

You can point out if I am printing logs in wrong way.
and you will see logs like this,

![image](https://user-images.githubusercontent.com/24878579/160283533-6c190707-b9ba-4abd-994a-4ad96147e83b.png)

ofcourse zero_grad is happening for batch_index = 1 but after forward pass completes for batch_index = 1.

**Comment by abdurrehman11** [comment]
Also, I just recap myself about zero_grad and actually it has nothing to do with forward pass instead it must happen before backward pass so I logged backward pass as well but still same issue as you can see below.

zero_grad before backward pass:
https://discuss.pytorch.org/t/should-we-perform-optimizer-zero-grad-before-we-do-forward-pass-or-after-that/14254

![image](https://user-images.githubusercontent.com/24878579/160284065-19cca55d-da71-4027-af66-81348b893fb6.png)

**Comment by abhishekkrthakur** [comment]
ohh! thanks for the code. i got it now and I've fixed it in main branch. many thanks for looking deep into the codebase 🙏🏽

**Comment by abdurrehman11** [comment]
Thanks for considering the issue and quick fix. This repo is really great and keeps updating it with awesome stuff!
